# Generated by Django 3.1.2 on 2020-10-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_auto_20201005_1732"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_id", models.CharField(max_length=128)),
                ("message", models.JSONField(blank=True, null=True)),
                ("edited_message", models.JSONField(blank=True, null=True)),
                ("channel_post", models.JSONField(blank=True, null=True)),
                ("edited_channel_post", models.JSONField(blank=True, null=True)),
                ("inline_query", models.JSONField(blank=True, null=True)),
                ("chosen_inline_result", models.JSONField(blank=True, null=True)),
                ("callback_query", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
