# Generated by Django 3.1.2 on 2020-10-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_telegramupdate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="TelegramUser",
        ),
    ]
